name: Java CI with Gradle
defaults:
  run:
    working-directory: ./app

on:
  push:
    branches: [ main ]

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew test
    - name: Run checkstyle
      run: ./gradlew checkstyleMain
    - name: Create a test coverage report
      run: ./gradlew jacocoTestReport
    - name: Send data to codecov
      run: bash <(curl -s https://codecov.io/bash)
